version: 0.0
os: linux

files:
  - source: agent/target/agent.jar
    destination: /opt
file_exists_behavior: OVERWRITE

hooks:
  BeforeInstall:
    - location: scripts/stop_service.sh
      timeout: 60
      runas: root
  AfterInstall:
    - location: scripts/set_perms.sh
      timeout: 60
      runas: root
  ApplicationStart:
    - location: scripts/start_service.sh
      timeout: 60
      runas: root
  ValidateService:
    - location: scripts/health_check.sh
      timeout: 60
      runas: root